### ISSUE TITLE
Update versions in starter branch

### ISSUE THREAD

**Issue by dvvanessastoiber** [Caleydo/ordino_product#28]
We should update all repos in _phovea_product.json_ to the latest versions.

**Comment by thinkh** [comment]
@dvvanessastoiber I updated the versions to the Ordino v7.0.1 release with commit https://github.com/Caleydo/ordino_product/commit/bfa05b59b980d0d75b961a73c0263de04a1a33d8. However, the CircleCI build is failing, because tdp_dummy is not updated and released (e.g., with dist folder). Could you please update and release tdp_dummy? Afterwards you can trigger a rebuild of the starter branch.

**Comment by thinkh** [comment]
I've updated the Docker images for Ordino Starter on Docker Hub:

* https://hub.docker.com/r/caleydo/ordino/
* https://hub.docker.com/r/caleydo/ordino_server/
